apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: app-nginx
  name: app-nginx
spec:
  containers:
  - image: nginx
    name: app-nginx
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
