apiVersion: v1
kind: Pod
metadata:
  labels:
    run: Apps
  name: pod-limit
spec:
  containers:
  - image: nginx
    name: webserver
    resources:
      limits:
        cpu: "1"
        memory: "128Mi"
      requests:
        cpu: "0.5"
        memory: "64Mi"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  # Especificações do volume definido anteriormente.
  volumes:
  - name: emptydirname
    emptyDir:
      sizeLimit: 256Mi

