apiVersion: v1
kind: Pod
metadata:
  labels:
    run: Apps
  name: pod-limit
spec:
  containers:
  - image: ubuntu
    name: ubuntu
    args:
      - sleep
      - "1200"
    resources:
      # Determina o limite máximo de recurso disponível.
      limits:
        cpu: "0.5"
        memory: "128Mi"
      # Garante limite de recurso especificado para o container.
      requests:
        cpu: "0.3"
        memory: "64Mi"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
