apiVersion: v1
kind: Pod
metadata:
  labels:
    run: pod-nginx
    service: webapp
  name: pod-nginx
spec:
  containers:
  - image: nginx
    name: webapp
    resources: {}
  - image: busybox
    name: busybox
    args:
      - sleep
      - "600"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
