apiVersion: v1
kind: Pod
metadata:
  labels:
    run: Apps
  name: pod-limit
spec:
  containers:
  - image: ubuntu
    name: ubuntu
    args:
      - sleep
      - "600"
  - image: nginx
    name: webserver
    # Definição do volume (EnptyDir) do container
    volumeMounts:
      # Ponto de montagem
    - mountPath: /dados
      name: emptydirname
    resources:
      # Determina o limite máximo de recurso disponível.
      limits:
        cpu: "1"
        memory: "128Mi"
      # Garante limite de recurso especificado para o container.
      requests:
        cpu: "0.5"
        memory: "64Mi"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  # Especificações do volume definido anteriormente.
  volumes:
  - name: emptydirname
    emptyDir:
      sizeLimit: 256Mi

