apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
    sercice: webserver
  name: hoax
spec:
  containers:
  - image: nginx
    name: nginx
    resources: {}
  - image: busybox
    name: busybox
    args:
    - sleep
    - "600"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
