# Deplyment spec
#
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-deplyment
    cloud: azure
  name: nginx-deployment
  namespace: biju
spec:
  replicas: 14
  selector:
    matchLabels:
      app: nginx-deployment
  strategy:
    type: Recreate
# Pods spec
#
  template:
    metadata:
      labels:
        app: nginx-deployment
# Container spec
#
    spec:
      containers:
      - image: nginx:1.17.0
        name: nginx-azure # Container's name
        resources:
          limits:
            cpu: "0.7"
            memory: "256Mi"
          requests:
            cpu: "0.3"
            memory: "64Mi"
