# Deplyment spec
#
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-deployment
  name: nginx-deployment
  namespace: biju
spec:
  replicas: 24
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: nginx-deployment
# Deployment update strategy
#
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
# Pods spec
#
  template:
    metadata:
      labels:
        app: nginx-deployment
# Container spec
#
    spec:
      containers:
      - image: nginx:1.15.0
        name: pod-nginx # Container's name
        resources:
          limits:
            cpu: "1"
            memory: "256Mi"
          requests:
            cpu: "0.5"
            memory: "64Mi"
