### Manifesto criado com --dry-run
#
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: app-nginx
  name: app-nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-nginx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: app-nginx
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
