apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: adugue
  name: adugue
spec:
  containers:
  - image: nginx
    name: adugue
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
